version: "3.8"

services:
  lobe-chat:
    image: lobehub/lobe-chat
    restart: always
    ports:
      - "172.17.0.1:57392:3210"
    environment:
      OPENAI_API_KEY: sk-xxxx
      ACCESS_CODE: lobe66
